export const Permission = {
  None: 0,
  PersonRead: 1 << 0,
  PersonWrite: 1 << 1,
  PersonDelete: 1 << 2,
  ParticipationRead: 1 << 3,
  ParticipationWrite: 1 << 4,
  ParticipationDelete: 1 << 5,
  BoardRead: 1 << 6,
  BoardWrite: 1 << 7,
  BoardDelete: 1 << 8,
  ReportRead: 1 << 9,
  ReportGenerate: 1 << 10,
  UserRead: 1 << 11,
  UserWrite: 1 << 12,
  UserDelete: 1 << 13,
  CountryRead: 1 << 14,
  CountryWrite: 1 << 15,
  CountryDelete: 1 << 16,
  DocumentTypeRead: 1 << 17,
  DocumentTypeWrite: 1 << 18,
  DocumentTypeDelete: 1 << 19,
  PositionRead: 1 << 20,
  PositionWrite: 1 << 21,
  PositionDelete: 1 << 22,
  Admin: ~0,
} as const;

export type PermissionFlag = (typeof Permission)[keyof typeof Permission];
